version: '3.4'

networks:
  ntwrk_backend: {}

services:
  db-server:
 #    image: microsoft/mssql-server-linux:2017-latest
      build:
        context: .
        dockerfile: MSSQL_RestoreBackups/Dockerfile
      restart: always
      container_name: db-server
      environment:
        SA_PASSWORD: "Alten1234"
        ACCEPT_EULA: "Y"
      ports:
        - "1400:1433"   
      networks:
        - ntwrk_backend

#  altenvehiclesms:
#      build:
#        context: .
#        dockerfile: AltenVehiclesMS/Dockerfile
#      restart: always
#      container_name: altenvehiclesms
#      ports:
#        - "1000:8080"
#      depends_on:
#        - db-server
#      networks:
#        - ntwrk_backend

  altencustomersms:
      build:
        context: .
        dockerfile: AltenCustomersMS/Dockerfile
      restart: always
      container_name: altencustomersms
      ports:
        - "2000:5001"
      depends_on:
        - db-server
      networks:
        - ntwrk_backend

 # vehiclespingsimulator:
 #     build:
 #       context: .
 #       dockerfile: VehiclesPingSimulator/Dockerfile
 #     restart: always
 #     container_name: vehiclespingsimulator
 #     ports:
 #       - "3000:8080"
 #     networks:
 #       - ntwrk_backend

