// <auto-generated />
using System;
using AltenVehiclesMS.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AltenVehiclesMS.Migrations
{
    [DbContext(typeof(VehicleContext))]
    partial class VehicleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AltenVehiclesMS.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<string>("CustomerName");

                    b.Property<DateTime?>("LastSeen");

                    b.Property<string>("Regnr");

                    b.Property<string>("VIN");

                    b.HasKey("ID");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new { ID = 1, CustomerId = 1, CustomerName = "", Regnr = "ABC123", VIN = " YS2R4X20005399401" },
                        new { ID = 2, CustomerId = 1, CustomerName = "Kalles Grustransporter AB", Regnr = "DEF456", VIN = "VLUR4X20009093588" },
                        new { ID = 3, CustomerId = 1, CustomerName = "Kalles Grustransporter AB", Regnr = "GHI789", VIN = "VLUR4X20009048066" },
                        new { ID = 4, CustomerId = 2, CustomerName = "Johans Bulk AB ", Regnr = "JKL012", VIN = "YS2R4X20005388011" },
                        new { ID = 5, CustomerId = 2, CustomerName = "Johans Bulk AB ", Regnr = "MNO345", VIN = "YS2R4X20005387949" },
                        new { ID = 6, CustomerId = 3, CustomerName = "Haralds Värdetransporter AB", Regnr = "PQR678", VIN = "VLUR4X20009048066" },
                        new { ID = 7, CustomerId = 3, CustomerName = "Haralds Värdetransporter AB", Regnr = "STU901", VIN = "YS2R4X20005387055" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
